import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
const browser = await chromium.launch({headless:true});
const page = await browser.newPage({viewport:{width:1440,height:1000}});
page.on('console',m=>{if(m.type()==='error')console.log(m.text().slice(0,150))});
await page.goto('https://pagamento.nova381.online//',{waitUntil:'networkidle'});
await page.screenshot({path:'reference/original-desktop.png',fullPage:true});
await fs.writeFile('reference/original-body.html',await page.locator('body').first().innerHTML());
await fs.writeFile('reference/original-styles.css',await page.locator('style').evaluateAll(els=>els.map(e=>e.textContent).join('\n')));
console.log(await page.locator('body').first().innerText());
console.log('links',await page.locator('a').evaluateAll(els=>els.map(e=>({text:e.textContent,href:e.getAttribute('href')}))));
await browser.close();
